# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# - see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Typing via mypy


on:
  push:
    branches: [ "master", "stable" ]
    paths: ["custom_components/**.py", "tests/**.py", "src/**/py.typed", ".github/workflows/type-type.yml"]

  pull_request:
    branches: [ "master", "stable" ]
    paths: ["custom_components/**.py", "tests/**.py", "src/**/py.typed", ".github/workflows/type-type.yml"]

  workflow_dispatch:


jobs:
  type:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Check with mypy
        run: mypy

      - run: echo "🍏 This job's status is ${{ job.status }}."
