# This workflow will...
# - see: https://docs.astral.sh/ruff/integrations/#github-actions

name: Linting via ruff (check)


on:
  push:
    branches: [ "master", "stable" ]
    paths: [
        ".github/workflows/check-lint.yml",
        "custom_components/**.py",
        "tests/**",
    ]

  pull_request:
    branches: [ "master", "stable" ]
    paths: [
        ".github/workflows/check-lint.yml",
        "custom_components/**.py",
        "tests/**",
    ]

  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check with ruff
        run: ruff check --output-format=github .

      - run: echo "🍏 This job's status is ${{ job.status }}."
